export const FETCH_DECKS_BEGIN = 'FETCH_DECKS_BEGIN';
export const FETCH_DECKS_SUCCESS = 'FETCH_DECKS_SUCCESS';
export const FETCH_DECKS_ERROR = 'FETCH_DECKS_ERROR';

export const ADD_DECK_BEGIN = 'ADD_DECK_BEGIN';
export const ADD_DECK_SUCCESS = 'ADD_DECK_SUCCESS';
export const ADD_DECK_ERROR = 'ADD_DECK_ERROR';

export const CLEAR_DECKS_BEGIN = 'CLEAR_DECKS_BEGIN';
export const CLEAR_DECKS_SUCCESS = 'CLEAR_DECKS_SUCCESS';
export const CLEAR_DECKS_ERROR = 'CLEAR_DECKS_ERROR';

export const DELETE_DECK_BEGIN = 'DELETE_DECK_BEGIN';
export const DELETE_DECK_SUCCESS = 'DELETE_DECK_SUCCESS';
export const DELETE_DECK_ERROR = 'DELETE_DECK_ERROR';

export const ADD_CARD_BEGIN = 'ADD_CARD_BEGIN';
export const ADD_CARD_SUCCESS = 'ADD_CARD_SUCCESS';
export const ADD_CARD_ERROR = 'ADD_CARD_ERROR';